### ISSUE TITLE
bug report: drown warnings

### ISSUE THREAD

**Issue by Li0nsDickachu** [Git-Forked/ouch#2]
the code checks for air when the player gets damaged to see if they are drowning. this means if I fall into a piece of tall grass, this mod thinks I am drowning when in fact I only received fall damage. this also means if I am in water and a mob hurts me, this mod thinks I am drowning. it would help to check for liquids in the position the players head is in, instead of checking for air in the player's feet, but that does not completely resolve the issue.

**Comment by Git-Forked** [comment]
This is not a bug but a limitation of the Minetest client-side modding API.  The Minetest client-side modding API is experimental and doesn't offer many features at this time, and may never.  Currently I see no methods of fixing this.  Feel free to fork the mod and experiment on your own if you wish.  If you can come up with a working solution, share it back.  This mod was created to offer some fun and warning sounds to taking damage as best as was possible.  The alternative is going back to the way the game was originally designed without any sounds to alert to damage at all.

**Comment by Li0nsDickachu** [comment]
while working on my own clientside mod based on your mod, I found the fix to this bug. simply replace "if is_player_in_air() == false then" with "if minetest.localplayer:get_breath(self) == 0 then". this way it only gets triggered if you are out of breath. of course it would still be triggered erroneously if you were drowning and being attacked at the same time, but that is a lot less noticeable. the documentation for the localplayer object is practically missing so it took me quite a while to figure it out.

**Comment by Git-Forked** [comment]
That throws a Lua warning:  accessing undefined variable 'self'
After a bit more investigation, I think that will solve itself once the script is imported into the main Minetest at mod load, which Lua Linter cannot detect from checked as a separate script.
